services:
  timescale:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_PASSWORD: Password12!
      POSTGRES_DB: DubUrl
    ports:
      - "5432:5432"
    volumes:
      - ./initialize.sql:/docker-entrypoint-initdb.d/initialize.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d DubUrl" ]
      interval: 2s
      timeout: 5s
      retries: 30
