# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" 
    directory: "/DubUrl.Core/" 
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"
  - package-ecosystem: "nuget" 
    directory: "/DubUrl.OleDb/" 
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"
  - package-ecosystem: "nuget" 
    directory: "/DubUrl.Extensions/" 
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"
  - package-ecosystem: "nuget" 
    directory: "/DubUrl.Adomd/" 
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"
  - package-ecosystem: "nuget" 
    directory: "/DubUrl.Testing/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"
  - package-ecosystem: "nuget" 
    directory: "/DubUrl.OleDb.Testing/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"
  - package-ecosystem: "nuget" 
    directory: "/DubUrl.Extensions.Testing/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"      
  - package-ecosystem: "nuget" 
    directory: "/DubUrl.Adomd.Testing/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"     
  - package-ecosystem: "nuget" 
    directory: "/DubUrl.QA/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"
