# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" 
    directories:
      - "/DubUrl.*/" 
    schedule:
      interval: "daily"
    labels:
      - "dependency-update"
    commit-message:
      prefix: "chore"
    ignore:
      - dependency-name: "Net.IBM.Data.Db2"
    groups:
      NUnit:
          patterns:
            - "NUnit"
      NUnit.Analyzers:
          patterns:
            - "NUnit.Analyzers"
      Microsoft.NET.Test.Sdk:
          patterns:
            - "Microsoft.NET.Test.Sdk"
      Moq:
          patterns:
            - "Moq"
      Coverlet:
          patterns:
            - "coverlet.*"
      DotNet.ReproducibleBuilds:
          patterns:
            - "DotNet.ReproducibleBuilds"
      Microsoft.Extensions:
          patterns:
            - "Microsoft.Extensions*"
      Microsoft.Identity:
          patterns:
            - "Microsoft.Identity*"
      Microsoft.Data.SqlClient:
          patterns:
            - "Microsoft.Data.SqlClient"
      Microsoft.Data.Sqlite.Core:
          patterns:
            - "Microsoft.Data.Sqlite.Core"
      System.Data.Odbc:
          patterns:
            - "System.Data.Odbc"
      System.Data.OleDb:
          patterns:
            - "System.Data.OleDb"
      Npgsql :
          patterns:
            - "Npgsql"      
      DuckDB :
          patterns:
            - "DuckDB.NET.Data"
            - "DuckDB.NET.Bindings.Full"
      MySql.Data:
          patterns:
            - "MySql.Data"
      MySqlConnector:
          patterns:
            - "MySqlConnector"
      Oracle.ManagedDataAccess.Core:
          patterns:
            - "Oracle.ManagedDataAccess.Core"
      Snowflake.Data:
          patterns:
            - "Snowflake.Data"
      System:
          patterns:
            - "System.Management"
            - "System.Text.Json"
      SingleStoreConnector:
          patterns:
            - "SingleStoreConnector"
      FirebirdSql.Data.FirebirdClient:
          patterns:
            - "FirebirdSql.*"
