# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" 
    directories:
      - "/DubUrl.*/" 
    schedule:
      interval: "daily"
    labels:
      - "dependency-update"
    commit-message:
      prefix: "chore"
    groups:
      NUnit:
          patterns:
            - "NUnit"
      Microsoft.NET.Test.Sdk:
          patterns:
            - "Microsoft.NET.Test.Sdk"
      Moq:
          patterns:
            - "Moq"
      DotNet.ReproducibleBuilds:
          patterns:
            - "DotNet.ReproducibleBuilds"
      Microsoft.Data.SqlClient:
          patterns:
            - "Microsoft.Data.SqlClient"
      Microsoft.Data.Sqlite.Core:
          patterns:
            - "Microsoft.Data.Sqlite.Core"
      System.Data.Odbc:
          patterns:
            - "System.Data.Odbc"
      System.Data.OleDb:
          patterns:
            - "System.Data.OleDb"
      Net.IBM.Data.Db2:
          patterns:
            - "Net.IBM.Data.Db2"
      Npgsql :
          patterns:
            - "Npgsql"      
      DuckDB :
          patterns:
            - "DuckDB.NET.Data"
            - "DuckDB.NET.Bindings.Full"
