version: build.{build}
image: Visual Studio 2022

skip_commits:
  files:
    - docs/
    - misc/
    - README.md
    - LICENSE
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - SECURITY.md

environment:
  github_access_token:
    secure: gtEHCUmmDjYfrp/NEe2qUH3SBedD4Hc7VWVyvOOE5KmyYYQnFmtyH9sQpaD33nU5/dqeijEBdkdPzKQYuIrpmgiIt/OucnY8GoNcL6VR9WSVc1hCkhGMYLBjooeKOvBg

init:
- cmd: git config --global core.autocrlf true
- cmd: setx IGNORE_NORMALISATION_GIT_HEAD_MOVE "1"
- cmd: RefreshEnv.cmd
- pwsh: Write-Host "Target branch is '$($env:APPVEYOR_REPO_BRANCH)'"

before_build:
- cmd: gitversion /output buildserver /verbosity Minimal
- pwsh: Write-Host "Building DubUrl version $($env:GitVersion_SemVer)"

build_script:
  #- dotnet --info
  - dotnet build DubUrl.sln -p:version="%GitVersion_SemVer%" -c Release /p:ContinuousIntegrationBuild=true --nologo 

test_script:
- pwsh: |
    $ErrorActionPreference = "Stop"
    dotnet test DubUrl.Testing -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Threshold=10 /p:ThresholdType=line /p:CoverletOutput=../.coverage/DubUrl.xml --test-adapter-path:. --logger:Appveyor --no-build --nologo
    dotnet test DubUrl.OleDb.Testing -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Threshold=10 /p:ThresholdType=line /p:Exclude=[DubUrl.Testing]* /p:CoverletOutput=../.coverage/DubUrl.OleDb.xml --test-adapter-path:. --logger:Appveyor --no-build --nologo
    dotnet test DubUrl.Extensions.DependencyInjection.Testing -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Threshold=10 /p:ThresholdType=line /p:CoverletOutput=../.coverage/DubUrl.Extensions.DependencyInjection.xml --test-adapter-path:. --logger:Appveyor --no-build --nologo
    if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode )  }

- pwsh: |
    $ProgressPreference = 'SilentlyContinue'
    Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
    .\codecov.exe --dir "./coverage"

- pwsh: |
      $force = ($env:APPVEYOR_REPO_BRANCH -eq "main") #Valid for a Pull Request or a Commit on main
      & .\Duburl.QA\deploy-test-harness.ps1 -force:$force -config "Release" -frameworks @("net6.0") -exclude @("CockRoach", "Drill", "Trino")
      if ($lastexitcode -gt 0) {
        throw "At least one of the test-suite was not successful. Build stopped."
      }

after_test:
- dotnet pack DubUrl.Core -p:version="%GitVersion_SemVer%" -c Release --include-symbols --no-build --nologo 
- dotnet pack DubUrl.OleDb -p:version="%GitVersion_SemVer%" -c Release --include-symbols --no-build --nologo 
- dotnet pack DubUrl.Extensions.DependencyInjection -p:version="%GitVersion_SemVer%" -c Release --include-symbols --no-build --nologo 

artifacts:
- path: '**\*.nupkg'
- path: '**\*.snupkg'

deploy:
- provider: NuGet
  api_key:
    secure: 6hBESdkEJj+a3ckY3Uw/2C55XRlG6/X9QKzb9IWl2/xMjxaJHy60lRxyOK4XQVWd
  skip_symbols: false
  artifact: /.*(\.|\.s)nupkg/
  on:
    branch: main

on_success:

  - pwsh: |
      & .\generate-adonet-info.ps1
      $exitCode = $LastExitCode
      & .\generate-odbc-driver-info.ps1
      $exitCode += $LastExitCode
      & .\generate-oledb-provider-info.ps1
      $exitCode += $LastExitCode
      if ($exitCode -gt 0) {
        Write-Host "`tUpdating README.md ..."
        & .\generate-table-scheme.ps1
        & .\generate-badge.ps1
        Write-Host "`tSetting GitHub credentials ..."
        & git config --global credential.helper store
        Set-Content -Path "$HOME\.git-credentials" -Value "https://Seddryck:$($env:github_access_token)@github.com`n" -NoNewline
        & git config --global user.email "no-reply@nbiguity.io"
        & git config --global user.name "AppVeyor bot"
        Write-Host "`tCreating commit ..."
        & git add --all
        & git status
        & git pull
        & git commit -m "Update automatically generated documentation related to schemes"
        Write-Host "`tPushing commit ..."
        & git push origin
        Write-Host "`tNew commit uploaded."
      }
