version: build.{build}
image: Visual Studio 2022

skip_commits:
  files:
    - docs/
    - misc/
    - README.md
    - LICENSE

environment:
  github_access_token:
    secure: j31Dt6ak1HtS5PTfhwc/He4jeCesBw9GULDRlPhNLjwBQEgFivhypRi5m4M7o3cb

init:
  - cmd: git config --global core.autocrlf true
  - ps: $env:IGNORE_NORMALISATION_GIT_HEAD_MOVE = 1

before_build:
- cmd: gitversion /output buildserver /verbosity Minimal
- cmd: echo "Building DubUrl version %GitVersion_SemVer%"

build_script:
  #- dotnet --info
  - dotnet build DubUrl.sln -p:version="%GitVersion_SemVer%" -c Release /p:ContinuousIntegrationBuild=true --nologo 

test_script:
- dotnet test DubUrl.Testing -c Release --test-adapter-path:. --logger:Appveyor --no-build --nologo 
- dotnet test DubUrl.OleDb.Testing -c Release --test-adapter-path:. --logger:Appveyor --no-build --nologo 
- dotnet test DubUrl.Extensions.DependencyInjection.Testing -c Release --test-adapter-path:. --logger:Appveyor --no-build --nologo 
- pwsh: |
      & .\deploy-mssql-test-env.ps1 -force
      & .\deploy-pgsql-test-env.ps1 -force
      & .\deploy-mysql-test-env.ps1 -force
      & .\deploy-firebird-test-env.ps1 -force
      & .\deploy-msexcel-test-env.ps1 -force
      & .\deploy-text-test-env.ps1 -force

after_test:
- dotnet pack DubUrl.Core -p:version="%GitVersion_SemVer%" -c Release --include-symbols --no-build --nologo 
- dotnet pack DubUrl.OleDb -p:version="%GitVersion_SemVer%" -c Release --include-symbols --no-build --nologo 
- dotnet pack DubUrl.Extensions.DependencyInjection -p:version="%GitVersion_SemVer%" -c Release --include-symbols --no-build --nologo 

artifacts:
- path: '**\*.nupkg'
- path: '**\*.snupkg'

deploy:
- provider: NuGet
  api_key:
    secure: PTrp3h6emvTJJqdacXvOOBRAwrNqzZcXVaRp09YI8PhQqEcGXcOvSr1UeRRo8gOM
  skip_symbols: false
  artifact: /.*(\.|\.s)nupkg/
  on:
    branch: main

on_success:

  - pwsh: |
      & .\generate-scheme-info.ps1
      $exitCode = $LastExitCode
      & .\generate-odbc-driver-info.ps1
      $exitCode += $LastExitCode
      if ($exitCode -gt 0) {
        Write-Host "Update of README.md needed"
        & .\generate-table-scheme.ps1
        & git config --global credential.helper store
        Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:github_access_token):x-oauth-basic@github.com`n" -NoNewline
        & git config --global user.email "no-reply@nbiguity.io"
        & git config --global user.name "AppVeyor bot"
        & git add --all
        & git status
        & git commit -m "Update automatically generated documentation related to schemes"
        & git push origin
      }