version: build.{build}
image: Visual Studio 2022

init:
  - cmd: git config --global core.autocrlf true

before_build:
- cmd: gitversion /output buildserver /verbosity Minimal
- cmd: echo "Building DubUrl version %GitVersion_SemVer%"

build_script:
  #- dotnet --info
  - dotnet build DubUrl.sln -p:version="%GitVersion_SemVer%" -c Release /p:ContinuousIntegrationBuild=true --nologo 

test_script:
- dotnet test DubUrl.Testing -c Release --no-build --nologo 

after_test:
- dotnet pack DubUrl.Core -p:version="%GitVersion_SemVer%" -c Release --include-symbols --no-build --nologo 

artifacts:
- path: '**\*.nupkg'
- path: '**\*.snupkg'

deploy:
- provider: NuGet
  api_key:
    secure: PTrp3h6emvTJJqdacXvOOBRAwrNqzZcXVaRp09YI8PhQqEcGXcOvSr1UeRRo8gOM
  skip_symbols: false
  artifact: /.*(\.|\.s)nupkg/