services:
  singlestore:
    image: ghcr.io/singlestore-labs/singlestoredb-dev:latest
    environment:
      SINGLESTORE_LICENSE: ${SINGLESTORE_LICENSE:?SINGLESTORE_LICENSE is required}
      ROOT_PASSWORD: Password12!
    ports:
      - "3306:3306"
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "singlestore -pPassword12! -e 'select 1' || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 40
