CREATE DATABASE ".\..\bin\Release\net6.0\Customer.fdb";

CREATE TABLE Customer(
    CustomerId INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    FullName VARCHAR(50),
    BirthDate DATE
);

INSERT INTO Customer (FullName, BirthDate) VALUES 
    ('Nikola Tesla',        '1856-07-10');
INSERT INTO Customer (FullName, BirthDate) VALUES 
    ('Albert Einstein',    '1879-03-14');
INSERT INTO Customer (FullName, BirthDate) VALUES 
    ('John von Neumann',   '1903-12-28');
INSERT INTO Customer (FullName, BirthDate) VALUES 
    ('Alan Turing',        '1912-06-23');
INSERT INTO Customer (FullName, BirthDate) VALUES 
    ('Linus Torvalds',     '1969-12-28');

COMMIT;

CONNECT "C:\Program Files\Firebird\Firebird_4_0\Security4.fdb" USER SYSDBA PASSWORD masterkey;
CREATE OR ALTER USER fbUser PASSWORD 'Password12!';
COMMIT;

CONNECT ".\..\bin\Release\net6.0\Customer.fdb" USER SYSDBA PASSWORD masterkey;
GRANT SELECT ON Customer TO fbUser;
COMMIT;